trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  semanticVersion: '1.0.0'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'jesulink2514/techies.apigateway'
    command: 'buildAndPush'
    Dockerfile: 'apigateway.Dockerfile'
    tags: '$(semanticVersion)$(Build.Rev:rrr)'

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'jesulink2514/techies.client.api'
    command: 'buildAndPush'
    Dockerfile: 'client.api.Dockerfile'
    tags: '$(semanticVersion)$(Build.Rev:rrr)'

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'techies.client.stats.api'
    command: 'buildAndPush'
    Dockerfile: 'techies.client.stats.Dockerfile'
    tags: '$(semanticVersion)$(Build.Rev:rrr)'
