# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
name: $(semanticVersion)$(Rev:.r)
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  semanticVersion: '1.0.0'

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'jesulink2514/techies.apigateway'
    command: 'buildAndPush'
    Dockerfile: 'apigateway.Dockerfile'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'jesulink2514/techies.client.api'
    command: 'buildAndPush'
    Dockerfile: 'client.api.Dockerfile'
    tags: '$(Build.BuildNumber)'

- task: Docker@2
  inputs:
    containerRegistry: 'jesulink-docker'
    repository: 'techies.client.stats.api'
    command: 'buildAndPush'
    Dockerfile: 'techies.client.stats.Dockerfile'
    tags: '$(Build.BuildNumber)'
